const { v4: uuidv4 } = require('uuid');
const path = require('path');
const fs = require('fs-extra');
const AdmZip = require('adm-zip');

module.exports = async (req, res) => {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method tidak diizinkan' });
  }

  try {
    const { 
      htmlFilename, 
      iconFilename,
      appName, 
      packageName, 
      version, 
      permissions, 
      features,
      includeIcon 
    } = req.body;

    if (!htmlFilename || !appName || !packageName) {
      return res.status(400).json({ error: 'Data tidak lengkap' });
    }

    const uploadsDir = path.join('/tmp', 'xy2apk-uploads');
    const htmlFilePath = path.join(uploadsDir, 'html', htmlFilename);
    
    if (!fs.existsSync(htmlFilePath)) {
      return res.status(404).json({ error: 'File HTML tidak ditemukan' });
    }

    // Generate unique ID untuk proses ini
    const processId = uuidv4();
    const tempDir = path.join('/tmp', 'xy2apk-temp', processId);
    const outputDir = path.join('/tmp', 'xy2apk-apks', processId);

    // Buat direktori temporary
    fs.ensureDirSync(tempDir);
    fs.ensureDirSync(outputDir);

    // Ekstrak atau copy file HTML
    const fileExt = path.extname(htmlFilename).toLowerCase();
    const projectDir = path.join(tempDir, 'www');
    fs.ensureDirSync(projectDir);

    if (fileExt === '.zip') {
      const zip = new AdmZip(htmlFilePath);
      zip.extractAllTo(projectDir, true);
    } else {
      fs.copySync(htmlFilePath, path.join(projectDir, 'index.html'));
    }

    // Copy icon jika ada
    let iconData = null;
    if (iconFilename && includeIcon) {
      const iconPath = path.join(uploadsDir, 'icons', iconFilename);
      if (fs.existsSync(iconPath)) {
        const iconDest = path.join(projectDir, 'icon.png');
        fs.copySync(iconPath, iconDest);
        iconData = fs.readFileSync(iconPath, 'base64');
      }
    }

    // Buat manifest untuk APK
    const manifest = {
      appName: appName,
      packageName: packageName,
      version: version,
      versionCode: 1,
      permissions: permissions,
      features: features,
      icon: iconData,
      timestamp: new Date().toISOString(),
      buildId: processId
    };

    // Buat file APK (simulasi)
    const apkFilename = `${appName.replace(/[^a-z0-9]/gi, '_')}_${version}.apk`;
    const apkPath = path.join(outputDir, apkFilename);

    // Simulasi APK file dengan data manifest
    const apkContent = JSON.stringify(manifest, null, 2);
    fs.writeFileSync(apkPath, apkContent);

    // Buat file README
    const readmeContent = `
# APK Generated by XY2APK

Application: ${appName}
Package: ${packageName}
Version: ${version}
Build ID: ${processId}
Generated: ${new Date().toLocaleString()}

## Features:
- ${features.includes('splash') ? 'Splash Screen' : ''}
- ${features.includes('fullscreen') ? 'Fullscreen Mode' : ''}
- ${features.includes('admob') ? 'AdMob Support' : ''}
- ${features.includes('push') ? 'Push Notification' : ''}

## Permissions:
${permissions === 'full' ? '- Internet\n- Storage\n- Location\n- Camera' : 
  permissions === 'standard' ? '- Internet\n- Storage' : '- Internet'}

## Installation:
1. Download this APK file
2. Enable "Install from unknown sources" in Android settings
3. Open the APK file and follow installation steps

Powered by XY2APK - kell.com
`;
    fs.writeFileSync(path.join(outputDir, 'README.txt'), readmeContent);

    // Generate URL untuk download
    const apkUrl = `/api/download/${processId}/${encodeURIComponent(apkFilename)}`;

    res.status(200).json({
      success: true,
      message: 'APK berhasil dibuat!',
      apkUrl: apkUrl,
      apkInfo: {
        id: processId,
        filename: apkFilename,
        appName: appName,
        packageName: packageName,
        version: version,
        size: fs.statSync(apkPath).size,
        features: features,
        permissions: permissions,
        hasIcon: !!iconData,
        timestamp: new Date().toISOString(),
        downloadUrl: apkUrl
      }
    });

    // Auto-cleanup setelah 1 jam (Vercel Functions akan menghapus /tmp secara periodic)
    setTimeout(() => {
      fs.remove(tempDir).catch(() => {});
    }, 3600000);

  } catch (error) {
    console.error('Conversion error:', error);
    res.status(500).json({ error: 'Gagal mengonversi ke APK: ' + error.message });
  }
};