const express = require('express');
const app = express();

// Enable CORS
app.use((req, res, next) => {
    res.header('Access-Control-Allow-Origin', '*');
    res.header('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
    res.header('Access-Control-Allow-Headers', 'Content-Type, Authorization');
    next();
});

app.use(express.json());
app.use(express.urlencoded({ extended: true }));

// Health check endpoint - GET /api/health
app.get('/api/health', (req, res) => {
    res.json({
        status: 'healthy',
        service: 'XY2APK Converter',
        version: '1.0.0',
        timestamp: new Date().toISOString(),
        environment: process.env.VERCEL_ENV || 'production',
        endpoints: {
            health: 'GET /api/health',
            upload: 'POST /api/upload',
            convert: 'POST /api/convert',
            download: 'GET /api/download'
        }
    });
});

// Upload endpoint - POST /api/upload
app.post('/api/upload', (req, res) => {
    console.log('Upload request received');
    try {
        // Simulate file upload
        const fileId = Date.now();
        
        res.json({
            success: true,
            message: 'File uploaded successfully (simulated)',
            files: {
                htmlFile: {
                    filename: `upload_${fileId}.html`,
                    originalname: req.body.filename || 'uploaded.html',
                    size: 2048,
                    mimetype: 'text/html'
                }
            }
        });
    } catch (error) {
        console.error('Upload error:', error);
        res.status(500).json({ 
            success: false,
            error: 'Upload failed'
        });
    }
});

// Convert endpoint - POST /api/convert
app.post('/api/convert', (req, res) => {
    console.log('Convert request received:', req.body);
    
    try {
        const { appName, packageName, version = '1.0.0' } = req.body;
        
        if (!appName || !packageName) {
            return res.status(400).json({
                success: false,
                error: 'App name and package name are required'
            });
        }
        
        const processId = Date.now().toString(36);
        const apkFilename = `${appName.replace(/[^a-z0-9]/gi, '_')}_${version}.apk`;
        
        // Get current URL for download link
        const protocol = req.headers['x-forwarded-proto'] || 'http';
        const host = req.headers['x-forwarded-host'] || req.headers.host;
        const baseUrl = `${protocol}://${host}`;
        
        res.json({
            success: true,
            message: 'APK created successfully!',
            apkInfo: {
                id: processId,
                filename: apkFilename,
                appName,
                packageName,
                version,
                size: Math.floor(Math.random() * 5000000) + 1000000, // 1-5MB
                features: req.body.features || [],
                permissions: req.body.permissions || 'standard',
                hasIcon: req.body.includeIcon || false,
                timestamp: new Date().toISOString(),
                downloadUrl: `${baseUrl}/api/download?id=${processId}&filename=${encodeURIComponent(apkFilename)}`
            }
        });
    } catch (error) {
        console.error('Convert error:', error);
        res.status(500).json({
            success: false,
            error: 'Conversion failed: ' + error.message
        });
    }
});

// Download endpoint - GET /api/download
app.get('/api/download', (req, res) => {
    console.log('Download request:', req.query);
    
    try {
        const { id, filename } = req.query;
        const downloadFilename = filename || 'app.apk';
        
        if (!id) {
            return res.status(400).json({
                success: false,
                error: 'Build ID is required'
            });
        }
        
        // Create simulated APK content
        const apkContent = `XY2APK Generated APK
========================

Build ID: ${id}
Filename: ${downloadFilename}
Generated: ${new Date().toLocaleString()}
Platform: Android
Status: Simulated APK for testing

This is a simulated APK file generated by XY2APK.
In production, this would be a real Android APK file.

Application Details:
- Generated by XY2APK Converter
- Powered by Kell
- Serverless on Vercel

Note: This file is for demonstration purposes only.
To get a real APK, implement Cordova/Android SDK integration.

Thank you for using XY2APK!`;
        
        res.setHeader('Content-Type', 'application/vnd.android.package-archive');
        res.setHeader('Content-Disposition', `attachment; filename="${downloadFilename}"`);
        res.setHeader('X-APK-ID', id);
        res.setHeader('X-Generated-By', 'XY2APK');
        
        res.send(apkContent);
        
    } catch (error) {
        console.error('Download error:', error);
        res.status(500).json({
            success: false,
            error: 'Download failed: ' + error.message
        });
    }
});

// Recent APKs endpoint - GET /api/recent-apks
app.get('/api/recent-apks', (req, res) => {
    res.json({
        success: true,
        count: 0,
        apks: [],
        message: 'No recent APKs found (simulation mode)'
    });
});

// Serve static files from public directory
app.use(express.static('public'));

// Handle all other routes - serve index.html
app.get('*', (req, res) => {
    if (req.path.startsWith('/api/')) {
        // If it's an API route that doesn't exist
        res.status(404).json({
            success: false,
            error: `API endpoint ${req.path} not found`
        });
    } else {
        // Serve the SPA for all other routes
        const path = require('path');
        res.sendFile(path.join(__dirname, '../public/index.html'));
    }
});

// Error handling middleware
app.use((err, req, res, next) => {
    console.error('Server error:', err);
    res.status(500).json({
        success: false,
        error: 'Internal server error',
        message: process.env.NODE_ENV === 'development' ? err.message : undefined
    });
});

module.exports = app;
